### PR TITLE
Small Spelling Fix

### PR DESCRIPTION
**Pull request by irishgordo**
- adjust the spelling for the word "wildly"

Resolves: patch/small-spelling-fix

### CODE REVIEW

**Comment by irishgordo** [comment]
I'm really excited about everything that all of y'all at Nightfall have been working on!
Wanted to update this awesome guide with a small spelling fix.

**Comment by irishgordo** [comment]
Super open to make any needed changes to this as well!
Just let me know, I'll make those adjustments and push up another commit!
:smiley: :+1:

**Comment by irishgordo** [comment]
Hi there, 

If there's no intention of wanting to merge in this small fix I can go ahead and close this Pull Request if you'd like :)
Just let me know :)

**Comment by rssathe** [comment]
@irishgordo sorry for the delay. Approved!

**Review by rssathe — APPROVED** [review]

**Comment by irishgordo** [comment]
Awesome @rssathe  :+1:  :)
No worries on the delay, I know how busy things can get :) 
Glad I could help!!

**Pull request merged**
